name: AstralShop
main: kr.starly.astralshop.AstralShopPlugin
website: https://starly.kr/
authors:
  - Nick
  - NillPoe

version: 3.1
api-version: 1.13

depend:
  - StarlyCore

softdepend:
  - PlaceholderAPI
  - Vault

commands:
  shopadmin:
    aliases: [ 상점관리 ]
  shop:
    aliases: [ 상점 ]