name: AstralShop
main: kr.starly.astralshop.AstralShop
website: https://starly.kr/
authors:
  - Nick
  - NillPoe

version: 1.0
api-version: 1.13

depend:
  - Vault

commands:
  shopadmin:
    aliases: [ 상점관리 ]
  shop:
    aliases: [ 상점 ]
  shopitem:
  test: