name: AstralShop
main: kr.starly.astralshop.AstralShopPlugin
website: https://starly.kr/
authors:
  - Nick
  - NillPoe

version: 3.2
api-version: 1.18

depend:
  - NillLibs

softdepend:
  - PlaceholderAPI
  - Vault

commands:
  shopadmin:
    aliases: [ 상점관리 ]
  shop:
    aliases: [ 상점 ]