name: AstralShop
main: xyz.starly.astralshop.AstralShop
website: https://starly.xyz
authors:
  - Nick
  - apEnrl

version: 1.0
api-version: 1.13

depend:
  - Vault

commands:
  shopitem:
  shopadmin:
    aliases: [ 상점관리 ]